geekshop/adminapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    # path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='categories'),
    # path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<pk>', adminapp.product_create, name='product_create'),
    path('products/read/category/<pk>', adminapp.products, name='products'),
    # path('products/read/<pk>', adminapp.product_read, name='product_read'),
    path('products/read/<pk>', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),

    path('orders/', adminapp.OrderListView.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.OrderUpdateView.as_view(), name='order_update'),

]

geekshop/authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('delete/<int:pk>/', basketapp.delete, name='delete'),
    path('remove/ajax/<int:pk>/', basketapp.basket_remove_ajax, name='remove_ajax'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('', include('social_django.urls', namespace='social')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),

    # path('admin/', admin.site.urls),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/<page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/ordersapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderDetailView.as_view(), name='order_read'),
    path('edit/<int:pk>/', ordersapp.OrderUpdateView.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDeleteView.as_view(), name='order_delete'),
    path('complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    discription = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True, verbose_name='активна', db_index=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=128, verbose_name='Название')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='Картинка')
    short_desc = models.CharField(max_length=120, verbose_name='Краткое описание')
    discription = models.TextField(verbose_name='Описание', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='Цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество на складе')
    is_active = models.BooleanField(default=True, verbose_name='активна', db_index=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def main(request):
    # products = Product.objects.all()[:4]
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:3]
    content = {
        'title': 'Главная',
        'products': products,
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', content)


# def get_basket(user):
#     if user.is_authenticated:
#         return Basket.objects.filter(user=user)
#     return []

def get_hot_product():
    products_list = Product.objects.all()
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    return Product.objects.filter(category__pk=hot_product.category.pk).exclude(pk=hot_product.pk)[:3]


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category = {'name': 'все', 'pk': 0}
        else:
            # category = ProductCategory.objects.get(pk=pk)
            category = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)
            # products_list = Product.objects.filter(Q(category__pk=1) | Q(category__pk=2))

        paginator = Paginator(products_list, 4)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category,
            # 'basket': quantity_and_price
            # 'basket': get_basket(request.user),
            'hot_product': get_hot_product(),
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': 'Продукты',
        'links_menu': links_menu,
        # 'basket': get_basket(request.user),
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    content = {
        'title': 'Контакты',
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/contact.html', content)


def not_found(request, exception):
    return render(request, '404.html', {'item': 'item'}, status=404)

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="/products/0"
            {% if request.resolver_match.2.pk == 0 %}class="active"{% endif %}>
            все
        </a>
    </li>
    {% for link in links_menu %}
        <li>
            <a href="/products/{{ link.id }}"
               {% if request.resolver_match.2.pk == link.id %}class="active"{% endif %}
            >{{ link.name }}</a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/includes/inc_contacts.html
<div class="location">
    {% for contact in contacts%}
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>{{ contact.city }}</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>{{ contact.phone }}</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>{{ contact.email }}</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>{{ contact.adres }}</p>
            </div>
        </div>
    {% endfor %}
</div>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<ul class="menu">
    <li>
        <a href="{% url 'main' %}" {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>домой</a>
    </li>
    <li>
        <a href="{% url 'mainapp:index' %}"
           {% if request.resolver_match.namespace == 'mainapp' %}class="active"{% endif %}>продукты</a></li>
    <li>
        <a href="{% url 'contacts' %}" {% if request.resolver_match.url_name == 'contacts' %}class="active"{% endif %}>контакты</a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <a href="{% url 'admin:users' %}">
            Админка
        </a>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
    {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
    {% endif %}
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:view' %}" class="basket">
    <span>
{#        {% if basket%}{{ basket.0 }}шт. {{ basket.1 }}р.{% endif %}#}
        {% if basket %}{{ basket.0.total_quantity }} шт. {{ basket.0.total_cost|floatformat:0 }} руб.{% endif %}
    </span>
</a>