geekshop/adminapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    # path('users/read/', adminapp.users, name='users'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    # path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    # path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    # path('categories/read/', adminapp.categories, name='categories'),
    path('categories/read/', adminapp.ProductCategoriesListView.as_view(), name='categories'),
    # path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<pk>', adminapp.product_create, name='product_create'),
    path('products/read/category/<pk>', adminapp.products, name='products'),
    # path('products/read/<pk>', adminapp.product_read, name='product_read'),
    path('products/read/<pk>', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),

    path('orders/', adminapp.OrderListView.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.OrderUpdateView.as_view(), name='order_update'),

]

geekshop/authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('', include('social_django.urls', namespace='social')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),

    # path('admin/', admin.site.urls),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from ordersapp.models import Order


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('status',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db.models.expressions import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm, OrderEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser


# Users
from mainapp.models import ProductCategory, Product


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'Админка'
#     users_list = ShopUser.objects.all().order_by('is_active')
#     content = {
#         'objects': users_list,
#         'title': title
#     }
#     return render(request, 'adminapp/users.html', content)
from ordersapp.models import Order


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    # ordering = ...
    # paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def user_create(request):
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#
#     content = {
#         'update_form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', content)


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    form_class = ShopUserRegisterForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def user_update(request, pk):
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserAdminEditForm(instance=edit_user)
#
#     content = {
#         'update_form': edit_form
#     }
#
#     return render(request, 'adminapp/user_update.html', content)


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи/редактирование'
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_delete(request, pk):
#     user_item = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         if user_item.is_active:
#             user_item.is_active = False
#         else:
#             user_item.is_active = True
#         user_item.save()
#         return HttpResponseRedirect(reverse('admin:users'))
#
#     content = {
#         'user_to_delete': user_item
#     }
#     return render(request, 'adminapp/user_delete.html', content)


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


# Categories

# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     new_category = ProductCategory()
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST, request.FILES, instance=new_category)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin:categories'))
#     else:
#         category_form = ProductCategoryEditForm()
#
#     content = {
#         'update_form': category_form
#     }
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    # fields = '__all__'  # без стилей
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def categories(request):
#     categories_list = ProductCategory.objects.all().order_by('is_active')
#     content = {
#         'objects': categories_list
#     }
#
#     return render(request, 'adminapp/categories.html', content)


class ProductCategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_category = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         edit_category.save()
#         return HttpResponseRedirect(reverse('adminapp:categories'))
#     else:
#         edit_form = ProductCategoryEditForm(instance=edit_category)
#
#     content = {
#         'update_form': edit_form
#     }
#
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    # fields = '__all__'  # без стилей
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
        return super().form_valid(form)

# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#
#     if request.method == 'POST':
#         if category_item.is_active:
#             category_item.is_active = False
#         else:
#             category_item.is_active = True
#         category_item.save()
#         return HttpResponseRedirect(reverse('admin:categories'))
#
#     content = {
#         'category_to_delete': category_item
#     }
#     return render(request, 'adminapp/category_delete.html', content)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        category_products = Product.objects.filter(category__pk=str(self.object.pk))

        if self.object.is_active:
            self.object.is_active = False
            for product in category_products:
                product.is_active = False
                product.save()
        else:
            self.object.is_active = True
            for product in category_products:
                product.is_active = True
                product.save()
        self.object.save()
        # self.object.is_active = False
        # self.object.save()

        return HttpResponseRedirect(self.get_success_url())


# Products

@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    category_item = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        update_form = ProductEditForm(request.POST, request.FILES)
        if update_form.is_valid():
            update_form.save()
            return HttpResponseRedirect(reverse('adminapp:products', args=[pk]))
    else:
        update_form = ProductEditForm()

    content = {
        'update_form': update_form,
        'category': category_item
    }

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    category_item = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category=category_item)

    content = {
        'objects': products_list,
        'category': category_item

geekshop/adminapp/templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>
            {{ title|title }}
        </title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>

<body>
  <div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin:category_create' %}>
        новая категория
      </a>
    </button>
		
    {% for object in object_list %}
      <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'admin:products' object.pk %}>
              товары категории
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_delete' object.pk %}>
              {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %} категорию {{ object.name }}
    ?
    <form action="{% url 'admin:category_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      {% if object.is_active %}
          <input class="btn btn-danger" type="submit" value="удалить">
      {% else %}
          <input class="btn btn-primary" type="submit" value="восстановить">
      {% endif %}
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/order_update.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:orders' order.pk %}">
      к списку заказов
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="orders_list">
    {% for object in object_list %}
      <div class="user_record {% if not object.is_active %}not_active{% endif %}">
          <button>
            <a href={% url 'admin:order_update' object.pk %}>
              редактировать
            </a>
          </button>
        <div class="user_name">
          <p><strong>{{ object.user.username }}</strong></p>
        </div>
        <div class="user_name">
          <p><strong>{{ object.status }}</strong></p>
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите
                {% if product_to_delete.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %} товар {{ product_to_delete.name }}
    ?
    <form action="{% url 'admin:product_delete' product_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      {% if product_to_delete.is_active %}
          <input class="btn btn-danger" type="submit" value="удалить">
      {% else %}
          <input class="btn btn-primary" type="submit" value="восстановить">
      {% endif %}
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:products' product_to_delete.category_id %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} /
                     {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
        <p>
        <button>
            <a href="{% url 'admin:product_delete' object.pk %}">
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
            </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin:products' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:products' category.pk %}">
      к списку товаров
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}
{% load static %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>
		
    {% for object in objects %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img src="{{ object.image|media_folder_products }}" alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:product_delete' object.pk %}">
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %} {{ object.username }}
    {% if object.first_name %}
      <b>{{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %}
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      {% if object.is_active %}
          <input class="btn btn-danger" type="submit" value="удалить">
      {% else %}
          <input class="btn btn-primary" type="submit" value="восстановить">
      {% endif %}
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load my_tags %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin:user_create' %}>
        новый пользователь
      </a>
    </button>
    {% for object in object_list %}
      <div class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img src="{% if object.shopuserprofile.avatar %}
                    {{ object.shopuserprofile.avatar|media_folder_users }}
                  {% else %}
                    {{ object.avatar|media_folder_users }}
                  {% endif %}" alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href={% url 'admin:user_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:user_delete' object.pk %}>
                {% if object.is_active %}
                    удалить
                {% else %}
                    восстановить
                {% endif %}
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	        <p>
                {% if object.first_name %}
                  <b>{{ object.first_name|title }}</b>
                    {% if object.last_name %}
                      <p>{{ object.last_name|title }}</p>
                    {% endif %}
                {% endif %}
            </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}