geekshop/authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.add, name='add'),
    path('delete/<int:pk>/', basketapp.delete, name='delete'),
    path('remove/ajax/<int:pk>/', basketapp.basket_remove_ajax, name='remove_ajax'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),

    path('', include('social_django.urls', namespace='social')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),

    # path('admin/', admin.site.urls),
]

handler404 = 'mainapp.views.not_found'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
   import debug_toolbar

   urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('<int:pk>/', mainapp.products, name='category'),
    path('<int:pk>/<page>/', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    discription = models.TextField(verbose_name='Описание')
    is_active = models.BooleanField(default=True, verbose_name='активна', db_index=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=128, verbose_name='Название')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='Картинка')
    short_desc = models.CharField(max_length=120, verbose_name='Краткое описание')
    discription = models.TextField(verbose_name='Описание', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='Цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество на складе')
    is_active = models.BooleanField(default=True, verbose_name='активна', db_index=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import random

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def main(request):
    # products = Product.objects.all()[:4]
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:3]
    content = {
        'title': 'Главная',
        'products': products,
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', content)


# def get_basket(user):
#     if user.is_authenticated:
#         return Basket.objects.filter(user=user)
#     return []

def get_hot_product():
    products_list = Product.objects.all()
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    return Product.objects.filter(category__pk=hot_product.category.pk).exclude(pk=hot_product.pk)[:3]


def products(request, pk=None, page=1):
    links_menu = ProductCategory.objects.filter(is_active=True)

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category = {'name': 'все', 'pk': 0}
        else:
            # category = ProductCategory.objects.get(pk=pk)
            category = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk)
            # products_list = Product.objects.filter(Q(category__pk=1) | Q(category__pk=2))

        paginator = Paginator(products_list, 4)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'products': products_paginator,
            'category': category,
            # 'basket': quantity_and_price
            # 'basket': get_basket(request.user),
            'hot_product': get_hot_product(),
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': 'Продукты',
        'links_menu': links_menu,
        # 'basket': get_basket(request.user),
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'

    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    content = {
        'title': 'Контакты',
        # 'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/contact.html', content)


def not_found(request, exception):
    return render(request, '404.html', {'item': 'item'}, status=404)

geekshop/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
	<div class="container">
        {% block menu %}
            <div class="hero-white">
                <div class="header clearfix">
                    <a href="/" class="logo"></a>
                    {% include 'mainapp/includes/inc_main_menu.html' %}
                </div>
            </div>
        {% endblock %}
    <div class="content">
        {% block content %}
        {% endblock %}
        <div class="clr"></div>
    </div>
	</div>
    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now 'Y' %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}
</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}
{% block content %}
    {% include 'mainapp/includes/inc_contacts.html' %}
    <div class="clr"></div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
{% endblock %}
{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
            <a href="#" class="search"></a>
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}
{% block content%}
    <div class="featured">
        <div class="featured-menu">
                <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
            <div class="block">
                <a href="#"><img src="/media/{{ product.image }}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
{#                    <img src="/media/products_images/{{ product.image }}" alt="{{ product.short_desc }}">#}
                    <img src="/media/products_images/{{ product.image }}" alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#">
                            <img src="/media/products_images/{{ product.image }}" alt="вариант 1">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/products_images/{{ product.image }}" alt="вариант 2">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/products_images/{{ product.image }}" alt="вариант 3">
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price">{{ product.price }} <span>руб.</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">{{ product.description }}</div>
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/products_images/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:1 }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>
                        {{ hot_product.short_desc }}
                    </p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                <div class="block">
                    <a href="#"><img style="height: 100%; width: 100%" src="/media/products_images/{{ same_products.0.image }}" alt="">
                        <div class="text">
                            <img src="/static/img/icon-hover.png" alt="img">
                            <h4>{{ same_products.0.name }}</h4>
                            <p>{{ same_products.0.short_desc }}</p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img style="height: 100%; width: 100%" src="/media/products_images/{{ same_products.1.image }}" alt="">
                        <div class="text">
                            <img src="/static/img/icon-hover.png" alt="img">
                            <h4>{{ same_products.1.name }}</h4>
                            <p>{{ same_products.1.short_desc }}</p>
                        </div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img style="height: 100%; width: 100%" src="/media/products_images/{{ same_products.2.image }}" alt="">
                        <div class="text">
                            <img src="/static/img/icon-hover.png" alt="img">
                            <h4>{{ same_products.2.name }}</h4>
                            <p>{{ same_products.2.short_desc }}</p>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>

    <div class="clr"></div>

</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="index.html" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
            <a href="#" class="search"></a>
            <a href="#" class="basket"></a>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                  {% if products.has_previous %}
                    <a href="{% url 'mainapp:page' category.pk products.previous_page_number %}">
                      <
                    </a>
                  {% endif %}
                  <span class="current">
                    страница {{ products.number }} из
                    {{ products.paginator.num_pages }}
                  </span>
                  {% if products.has_next %}
                    <a href="{% url 'mainapp:page' category.pk products.next_page_number %}">
                      >
                    </a>
                  {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
{#                    {% url 'basket:add' product.pk %}#}
                        <a href="{% url 'mainapp:product' product.pk %}">
                            <img style="height: 100%; width: 100%" src="/media/products_images/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png'%}" alt="hover-icon">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}